### PR TITLE
fix for https://github.com/jumph4x/canonical-rails/issues/15, due to to ...

### PR DESCRIPTION
**Pull request by IslamAzab**
...rack 1.4.5 failure to handle non string params

### CODE REVIEW

**Comment by jumph4x** [comment]
Thank you! Would you like a dot release for this?

**Comment by IslamAzab** [comment]
You are welcome and thank you too. :+1: Yeah it would be great.

**Comment by jumph4x** [comment]
I'll get that to you soon.

**Comment by jumph4x** [comment]
Here you go!

https://rubygems.org/gems/canonical-rails/versions/0.0.9

:tada:

**Pull request merged**
