### PR TITLE
Adding a config option to force the protocol

### PR DESCRIPTION
**Pull request by JohnRiv**
This fixes Issue #13

### CODE REVIEW

**Comment by jumph4x** [comment]
:tada:

**Comment by jumph4x** [comment]
LMK if you needa gem release for this.

**Comment by JohnRiv** [comment]
Thanks. I monkey patched this behavior in my project, so if you could do a gem release when you get a chance I'd appreciate it.

**Comment by jumph4x** [comment]
https://rubygems.org/gems/canonical-rails/versions/0.0.8 Here ya go

**Pull request merged**
