### PR TITLE
Support Rails 5.1 and test against Ruby 2.4.1

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
Hi @jhawthorn according to the discussion in #37, do you agree to merge it?

**Comment by jhawthorn** [comment]
This looks good to me :+1: :shipit:

**Comment by krzysiek1507** [comment]
@jumph4x could you please merge it and release new version? Thanks!

**Comment by jumph4x** [comment]
Thank you to everyone in this thread: @jhawthorn, @krzysiek1507.
The master is up to date, we are now at 0.2.0 and the release has been cut: https://rubygems.org/gems/canonical-rails/versions/0.2.0

**Pull request merged**
