### PR TITLE
Reduce Rails Dependency to Action View

### PR DESCRIPTION
**Pull request by BenMorganIO**
Once I removed the loading of the dummy application, it became crystal clear on what dependencies were required. ActionView is called in the codebase and ActionController is required by rspec-rails. Since I do not want to tinker with the actual test suite used, I included actionpack as a development dependency and used action view as our main rails dependency.

### CODE REVIEW

**Comment by jumph4x** [comment]
Is using a dummy application no longer the recommended path? As you noted, this PR changes from loading the dummy environment to loading specific railties.

**Comment by BenMorganIO** [comment]
It's still the recommended path when you need a dummy rails application. I just noticed that the specs didn't need it at all.

**Comment by jumph4x** [comment]
Excellent, let me review.

**Comment by jumph4x** [comment]
image

Initially unsuccessful in verifying that the dummy-app was not necessary, let me know what I am missing.

**Comment by BenMorganIO** [comment]
Let me know when a new version is cut.

**Pull request merged**
