### PR TITLE
Version bump for Rails 7.1.X

### PR DESCRIPTION
**Pull request by tellodaniel**

### CODE REVIEW

**Comment by tellodaniel** [comment]
@jumph4x What are your thoughts on this?

**Comment by tellodaniel** [comment]
@jumph4x friendly ping

**Comment by jumph4x** [comment]
Sorry, back at my desk. 

We will handle this ASAP.

**Comment by jumph4x** [comment]
https://rubygems.org/gems/canonical-rails/versions/0.2.16

**Pull request merged**
